package org.medTrade.persistance.model;

// Generated 23 déc. 2014 10:48:16 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CaracteristiquesProduits generated by hbm2java
 */
@Entity
@Table(name = "CaracteristiquesProduits", catalog = "MedTrade")
public class CaracteristiquesProduits implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4977127689086460234L;
	private int idCaracteristiquesProduits;
	private Article article;
	private String caractéristique;
	private String valeur;

	public CaracteristiquesProduits() {
	}

	public CaracteristiquesProduits(int idCaracteristiquesProduits,
			Article article) {
		this.idCaracteristiquesProduits = idCaracteristiquesProduits;
		this.article = article;
	}

	public CaracteristiquesProduits(int idCaracteristiquesProduits,
			Article article, String caractéristique, String valeur) {
		this.idCaracteristiquesProduits = idCaracteristiquesProduits;
		this.article = article;
		this.caractéristique = caractéristique;
		this.valeur = valeur;
	}

	@Id
	@Column(name = "idCaracteristiquesProduits", unique = true, nullable = false)
	public int getIdCaracteristiquesProduits() {
		return this.idCaracteristiquesProduits;
	}

	public void setIdCaracteristiquesProduits(int idCaracteristiquesProduits) {
		this.idCaracteristiquesProduits = idCaracteristiquesProduits;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Article_idArticle", nullable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@Column(name = "Caractéristique")
	public String getCaractéristique() {
		return this.caractéristique;
	}

	public void setCaractéristique(String caractéristique) {
		this.caractéristique = caractéristique;
	}

	@Column(name = "Valeur")
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

}
