package org.medTrade.persistance.model;

// Generated 25 déc. 2014 15:32:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "Categorie", catalog = "MedTrade")
public class Categorie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2016018116505072463L;
	private Integer idCategorie;
	private String categorie;
	private Integer categorieIdCategorie;
	private Set<Article> articles = new HashSet<Article>(0);

	public Categorie() {
	}

	public Categorie(String categorie, Integer categorieIdCategorie,
			Set<Article> articles) {
		this.categorie = categorie;
		this.categorieIdCategorie = categorieIdCategorie;
		this.articles = articles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCategorie", unique = true, nullable = false)
	public Integer getIdCategorie() {
		return this.idCategorie;
	}

	public void setIdCategorie(Integer idCategorie) {
		this.idCategorie = idCategorie;
	}

	@Column(name = "Categorie")
	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	@Column(name = "Categorie_idCategorie")
	public Integer getCategorieIdCategorie() {
		return this.categorieIdCategorie;
	}

	public void setCategorieIdCategorie(Integer categorieIdCategorie) {
		this.categorieIdCategorie = categorieIdCategorie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
