package org.medTrade.persistance.model;

// Generated 23 déc. 2014 10:48:16 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommandeClient generated by hbm2java
 */
@Entity
@Table(name = "CommandeClient", catalog = "MedTrade")
public class CommandeClient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7032724388082736206L;
	private int idCommandeClient;
	private Panier panier;
	private String code;
	private Date dateCreation;
	private Double montantHt;
	private Double taxes;
	private Double montantTtc;
	private Set<FactureClient> factureClients = new HashSet<FactureClient>(0);

	public CommandeClient() {
	}

	public CommandeClient(int idCommandeClient, Panier panier) {
		this.idCommandeClient = idCommandeClient;
		this.panier = panier;
	}

	public CommandeClient(int idCommandeClient, Panier panier, String code,
			Date dateCreation, Double montantHt, Double taxes,
			Double montantTtc, Set<FactureClient> factureClients) {
		this.idCommandeClient = idCommandeClient;
		this.panier = panier;
		this.code = code;
		this.dateCreation = dateCreation;
		this.montantHt = montantHt;
		this.taxes = taxes;
		this.montantTtc = montantTtc;
		this.factureClients = factureClients;
	}

	@Id
	@Column(name = "idCommandeClient", unique = true, nullable = false)
	public int getIdCommandeClient() {
		return this.idCommandeClient;
	}

	public void setIdCommandeClient(int idCommandeClient) {
		this.idCommandeClient = idCommandeClient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Panier_idPanier", nullable = false)
	public Panier getPanier() {
		return this.panier;
	}

	public void setPanier(Panier panier) {
		this.panier = panier;
	}

	@Column(name = "Code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreation", length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "MontantHT", precision = 22, scale = 0)
	public Double getMontantHt() {
		return this.montantHt;
	}

	public void setMontantHt(Double montantHt) {
		this.montantHt = montantHt;
	}

	@Column(name = "TAXES", precision = 22, scale = 0)
	public Double getTaxes() {
		return this.taxes;
	}

	public void setTaxes(Double taxes) {
		this.taxes = taxes;
	}

	@Column(name = "MontantTTC", precision = 22, scale = 0)
	public Double getMontantTtc() {
		return this.montantTtc;
	}

	public void setMontantTtc(Double montantTtc) {
		this.montantTtc = montantTtc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commandeClient")
	public Set<FactureClient> getFactureClients() {
		return this.factureClients;
	}

	public void setFactureClients(Set<FactureClient> factureClients) {
		this.factureClients = factureClients;
	}

}
