package org.medTrade.persistance.model;

// Generated 23 déc. 2014 10:48:16 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CommandeFournisseurHasArticle generated by hbm2java
 */
@Entity
@Table(name = "CommandeFournisseur_has_Article", catalog = "MedTrade")
public class CommandeFournisseurHasArticle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1506925634996678266L;
	private CommandeFournisseurHasArticleId id;
	private Article article;
	private CommandeFournisseur commandeFournisseur;
	private Integer qte;

	public CommandeFournisseurHasArticle() {
	}

	public CommandeFournisseurHasArticle(CommandeFournisseurHasArticleId id,
			Article article, CommandeFournisseur commandeFournisseur) {
		this.id = id;
		this.article = article;
		this.commandeFournisseur = commandeFournisseur;
	}

	public CommandeFournisseurHasArticle(CommandeFournisseurHasArticleId id,
			Article article, CommandeFournisseur commandeFournisseur,
			Integer qte) {
		this.id = id;
		this.article = article;
		this.commandeFournisseur = commandeFournisseur;
		this.qte = qte;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "commandeFournisseurIdCommandeFournisseur", column = @Column(name = "CommandeFournisseur_idCommandeFournisseur", nullable = false)),
			@AttributeOverride(name = "articleIdArticle", column = @Column(name = "Article_idArticle", nullable = false)) })
	public CommandeFournisseurHasArticleId getId() {
		return this.id;
	}

	public void setId(CommandeFournisseurHasArticleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Article_idArticle", nullable = false, insertable = false, updatable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CommandeFournisseur_idCommandeFournisseur", nullable = false, insertable = false, updatable = false)
	public CommandeFournisseur getCommandeFournisseur() {
		return this.commandeFournisseur;
	}

	public void setCommandeFournisseur(CommandeFournisseur commandeFournisseur) {
		this.commandeFournisseur = commandeFournisseur;
	}

	@Column(name = "Qte")
	public Integer getQte() {
		return this.qte;
	}

	public void setQte(Integer qte) {
		this.qte = qte;
	}

}
