package org.medTrade.persistance.model;

// Generated 23 déc. 2014 10:48:16 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommandeFournisseur generated by hbm2java
 */
@Entity
@Table(name = "CommandeFournisseur", catalog = "MedTrade")
public class CommandeFournisseur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8036171236644921614L;
	private int idCommandeFournisseur;
	private String code;
	private Date dateCreation;
	private String statut;
	private Set<CommandeFournisseurHasArticle> commandeFournisseurHasArticles = new HashSet<CommandeFournisseurHasArticle>(0);

	public CommandeFournisseur() {
	}

	public CommandeFournisseur(int idCommandeFournisseur) {
		this.idCommandeFournisseur = idCommandeFournisseur;
	}

	public CommandeFournisseur(int idCommandeFournisseur, String code,
			Date dateCreation, String statut, Set<CommandeFournisseurHasArticle> commandeFournisseurHasArticles) {
		this.idCommandeFournisseur = idCommandeFournisseur;
		this.code = code;
		this.dateCreation = dateCreation;
		this.statut = statut;
		this.commandeFournisseurHasArticles = commandeFournisseurHasArticles;
	}

	@Id
	@Column(name = "idCommandeFournisseur", unique = true, nullable = false)
	public int getIdCommandeFournisseur() {
		return this.idCommandeFournisseur;
	}

	public void setIdCommandeFournisseur(int idCommandeFournisseur) {
		this.idCommandeFournisseur = idCommandeFournisseur;
	}

	@Column(name = "Code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreation", length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "Statut")
	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commandeFournisseur")
	public Set<CommandeFournisseurHasArticle> getCommandeFournisseurHasArticles() {
		return this.commandeFournisseurHasArticles;
	}

	public void setCommandeFournisseurHasArticles(
			Set<CommandeFournisseurHasArticle> commandeFournisseurHasArticles) {
		this.commandeFournisseurHasArticles = commandeFournisseurHasArticles;
	}

}
