package org.medTrade.persistance.model;

// Generated 23 déc. 2014 10:48:16 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Conditionnement generated by hbm2java
 */
@Entity
@Table(name = "Conditionnement", catalog = "MedTrade")
public class Conditionnement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1565469525849798714L;
	private int idConditionnement;
	private String name;
	private Set<Article> articles = new HashSet<Article>(0);

	public Conditionnement() {
	}

	public Conditionnement(int idConditionnement) {
		this.idConditionnement = idConditionnement;
	}

	public Conditionnement(int idConditionnement, String name, Set<Article> articles) {
		this.idConditionnement = idConditionnement;
		this.name = name;
		this.articles = articles;
	}

	@Id
	@Column(name = "idConditionnement", unique = true, nullable = false)
	public int getIdConditionnement() {
		return this.idConditionnement;
	}

	public void setIdConditionnement(int idConditionnement) {
		this.idConditionnement = idConditionnement;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conditionnement")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
