package org.medTrade.persistance.model;

// Generated 23 déc. 2014 10:48:16 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FactureFournisseurHasArticle generated by hbm2java
 */
@Entity
@Table(name = "FactureFournisseur_has_Article", catalog = "MedTrade")
public class FactureFournisseurHasArticle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7887898879083537857L;
	private FactureFournisseurHasArticleId id;
	private Article article;
	private FactureFournisseur factureFournisseur;
	private Integer qte;

	public FactureFournisseurHasArticle() {
	}

	public FactureFournisseurHasArticle(FactureFournisseurHasArticleId id,
			Article article, FactureFournisseur factureFournisseur) {
		this.id = id;
		this.article = article;
		this.factureFournisseur = factureFournisseur;
	}

	public FactureFournisseurHasArticle(FactureFournisseurHasArticleId id,
			Article article, FactureFournisseur factureFournisseur, Integer qte) {
		this.id = id;
		this.article = article;
		this.factureFournisseur = factureFournisseur;
		this.qte = qte;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "factureFournisseurIdFactureFournisseur", column = @Column(name = "FactureFournisseur_idFactureFournisseur", nullable = false)),
			@AttributeOverride(name = "articleIdArticle", column = @Column(name = "Article_idArticle", nullable = false)) })
	public FactureFournisseurHasArticleId getId() {
		return this.id;
	}

	public void setId(FactureFournisseurHasArticleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Article_idArticle", nullable = false, insertable = false, updatable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FactureFournisseur_idFactureFournisseur", nullable = false, insertable = false, updatable = false)
	public FactureFournisseur getFactureFournisseur() {
		return this.factureFournisseur;
	}

	public void setFactureFournisseur(FactureFournisseur factureFournisseur) {
		this.factureFournisseur = factureFournisseur;
	}

	@Column(name = "Qte")
	public Integer getQte() {
		return this.qte;
	}

	public void setQte(Integer qte) {
		this.qte = qte;
	}

}
