package org.medTrade.persistance.model;

// Generated 23 déc. 2014 10:48:16 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name = "Images", catalog = "MedTrade")
public class Images implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3114674433641756038L;
	private int idImages;
	private Article article;
	private String path;

	public Images() {
	}

	public Images(int idImages, Article article) {
		this.idImages = idImages;
		this.article = article;
	}

	public Images(int idImages, Article article, String path) {
		this.idImages = idImages;
		this.article = article;
		this.path = path;
	}

	@Id
	@Column(name = "idImages", unique = true, nullable = false)
	public int getIdImages() {
		return this.idImages;
	}

	public void setIdImages(int idImages) {
		this.idImages = idImages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Article_idArticle", nullable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
