package org.medTrade.persistance.model;

// Generated 23 déc. 2014 10:48:16 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marque generated by hbm2java
 */
@Entity
@Table(name = "Marque", catalog = "MedTrade")
public class Marque implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7029711572165293901L;
	private Integer idMarque;
	private Marchant marchant;
	private String libelle;
	private Set<Article> articles = new HashSet<Article>(0);

	public Marque() {
	}

	public Marque(Marchant marchant) {
		this.marchant = marchant;
	}

	public Marque(Marchant marchant, String libelle, Set<Article> articles) {
		this.marchant = marchant;
		this.libelle = libelle;
		this.articles = articles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMarque", unique = true, nullable = false)
	public Integer getIdMarque() {
		return this.idMarque;
	}

	public void setIdMarque(Integer idMarque) {
		this.idMarque = idMarque;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Marchant_idMarchant", nullable = false)
	public Marchant getMarchant() {
		return this.marchant;
	}

	public void setMarchant(Marchant marchant) {
		this.marchant = marchant;
	}

	@Column(name = "Libelle")
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marque")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
