package org.medTrade.persistance.model;

// Generated 23 déc. 2014 10:48:16 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PanierHasArticle generated by hbm2java
 */
@Entity
@Table(name = "Panier_has_Article", catalog = "MedTrade")
public class PanierHasArticle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4782529885348507240L;
	private PanierHasArticleId id;
	private Article article;
	private Panier panier;
	private Integer qte;

	public PanierHasArticle() {
	}

	public PanierHasArticle(PanierHasArticleId id, Article article,
			Panier panier) {
		this.id = id;
		this.article = article;
		this.panier = panier;
	}

	public PanierHasArticle(PanierHasArticleId id, Article article,
			Panier panier, Integer qte) {
		this.id = id;
		this.article = article;
		this.panier = panier;
		this.qte = qte;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "panierIdPanier", column = @Column(name = "Panier_idPanier", nullable = false)),
			@AttributeOverride(name = "articleIdArticle", column = @Column(name = "Article_idArticle", nullable = false)) })
	public PanierHasArticleId getId() {
		return this.id;
	}

	public void setId(PanierHasArticleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Article_idArticle", nullable = false, insertable = false, updatable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Panier_idPanier", nullable = false, insertable = false, updatable = false)
	public Panier getPanier() {
		return this.panier;
	}

	public void setPanier(Panier panier) {
		this.panier = panier;
	}

	@Column(name = "Qte")
	public Integer getQte() {
		return this.qte;
	}

	public void setQte(Integer qte) {
		this.qte = qte;
	}

}
