package org.medTrade.persistance.model;

// Generated 23 déc. 2014 10:48:16 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PanierHasArticleId generated by hbm2java
 */
@Embeddable
public class PanierHasArticleId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6140128404697688495L;
	private int panierIdPanier;
	private int articleIdArticle;

	public PanierHasArticleId() {
	}

	public PanierHasArticleId(int panierIdPanier, int articleIdArticle) {
		this.panierIdPanier = panierIdPanier;
		this.articleIdArticle = articleIdArticle;
	}

	@Column(name = "Panier_idPanier", nullable = false)
	public int getPanierIdPanier() {
		return this.panierIdPanier;
	}

	public void setPanierIdPanier(int panierIdPanier) {
		this.panierIdPanier = panierIdPanier;
	}

	@Column(name = "Article_idArticle", nullable = false)
	public int getArticleIdArticle() {
		return this.articleIdArticle;
	}

	public void setArticleIdArticle(int articleIdArticle) {
		this.articleIdArticle = articleIdArticle;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PanierHasArticleId))
			return false;
		PanierHasArticleId castOther = (PanierHasArticleId) other;

		return (this.getPanierIdPanier() == castOther.getPanierIdPanier())
				&& (this.getArticleIdArticle() == castOther
						.getArticleIdArticle());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPanierIdPanier();
		result = 37 * result + this.getArticleIdArticle();
		return result;
	}

}
