package org.medTrade.persistance.model;

// Generated 26 déc. 2014 14:48:22 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "MedTrade")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5517284298196419195L;
	private Integer idUser;
	private Role role;
	private String login;
	private String password;
	private String nom;
	private String prenom;
	private String email;
	private Date dateCreation;
	private Boolean enabled;
	private Boolean locked;
	private Set<Marchant> marchants = new HashSet<Marchant>(0);

	public User() {
	}

	public User(Role role) {
		this.role = role;
	}

	public User(Role role, String login, String password, String nom,
			String prenom, String email, Date dateCreation, Boolean enabled,
			Boolean locked, Set<Marchant> marchants) {
		this.role = role;
		this.login = login;
		this.password = password;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.dateCreation = dateCreation;
		this.enabled = enabled;
		this.locked = locked;
		this.marchants = marchants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUser", unique = true, nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_idrole", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "Login")
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "Password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Nom")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prenom")
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreation", length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "Enabled")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "Locked")
	public Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Marchant> getMarchants() {
		return this.marchants;
	}

	public void setMarchants(Set<Marchant> marchants) {
		this.marchants = marchants;
	}

	@Override
	public String toString() {
		return "User [idUser=" + idUser + ", role=" + role + ", login=" + login
				+ ", password=" + password + ", nom=" + nom + ", prenom="
				+ prenom + ", email=" + email + ", dateCreation="
				+ dateCreation + ", enabled=" + enabled + ", locked=" + locked
				+ "]";
	}

}
